# Profile information
name: mushi720
title: mushi720 - Paulo França
description: > # this means to ignore newlines until "baseurl:"
  I will share here my experiences with Test Automation.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "mushi720.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
#facebook: #Add your Facebook
twitter: mushi720
#google-plus: #Add your Google+
github: Mushi720

# Contact form
#email: #your-email@domain.com

# Comments
#discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
